// import './globals.css'

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className='kekw'>{children}</body>
//     </html>
//   )
// }

// src/app/layout.js
import React from 'react';
import Navbar from '../../components/Navbar';
import "../globals.css"






const RootLayout= ({
  children,}) => {
  return (
    <div>
      <Navbar />
      <div className="container mx-auto my-4">{children}</div>
    </div>
  );
};

export default RootLayout;


//////



