// import './globals.css'

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className='kekw'>{children}</body>
//     </html>
//   )
// }

import { Router } from "next/navigation";
import "../globals.css"
import Footer from "@/components/Footer";

const RootLayout = ({
  children }) => {
  return (
    <html lang="en">
      <body className=" font-montserrat">
        {children}
        <Footer />
      </body>
      {/* <body className='bg-gradient-to-r from-slate-800 to-violet-800 '>
      <Navbar2 />
      <div className="container mx-auto my-8 mt-[256px] ">{children}</div>
      </body> */}

    </html>
  );
};

export default RootLayout;



